### ISSUE TITLE
DLRM ubench failing, possibly due to FBGEMM API update

### ISSUE THREAD

**Issue by amathews-amd** [facebookresearch/FAMBench#111]
```
Traceback (most recent call last):
  File "dlrm/ubench/dlrm_ubench_train_embeddingbag_driver.py", line 207, in <module>
    global_elap, global_bytes = run_emb(args, run_dataset)
  File "dlrm/ubench/dlrm_ubench_train_embeddingbag_driver.py", line 104, in run_emb
    requests = bench.split_table_batched_embeddings_benchmark.generate_requests(
TypeError: generate_requests() got an unexpected keyword argument 'weights_precision'
```
due to https://github.com/pytorch/FBGEMM/commit/4c581375

**Comment by amathews-amd** [comment]
cc: @jianyuh @nrsatish
